version: "3.8"
services:
  funder-frontend:
    build:
      context: ./funder-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - funder_network

  funder-backend:
    build:
      context: ./funder-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - funder_network

networks:
  funder_network:
    driver: bridge
